### PR TITLE
Fix list markdown in provider best practices

### PR DESCRIPTION
**Pull request by gene1wood**

### CODE REVIEW

**Review by caseysoftware — APPROVED** [review]

**Comment by caseysoftware** [comment]
Looks good. Thanks!

**Comment by sudobinbash** [comment]
Hi @gene1wood  👋

Thanks for contributing to webhooks.fyi.
We're launching our site on [Product Hunt tomorrow](https://www.producthunt.com/posts/webhooks-fyi) and I'd love to include our contributors as makers (to spread the love and street creds).

Please sign up to [producthunt.com](https://producthunt.com) and send me your profile url here if you would like to be included and I'll take care of the rest.

ty,
Fred

**Comment by gene1wood** [comment]
@sudobinbash No, I don't have a producthunt.com account. It looks like they require using a federated login (Google/Facebook/etc) instead of username/password and I'm reluctant to. I appreciate the offer though, thanks!

**Comment by sudobinbash** [comment]
Np Gene. Thanks for making webhooks.fyi awesome 🙌

**Pull request merged**
