### PR TITLE
Add Hookdeck to directory

### PR DESCRIPTION
**Pull request by leetrout**
This PR adds Hookdeck to the provider directory.

### CODE REVIEW

**Review by sudobinbash — CHANGES_REQUESTED** [review]
Hi @leetrout . 

Thanks for the PR <3. 


According to https://hookdeck.com/docs/destinations#receiving-webhook-events , Hookdeck  notifications are base64 encoded.

Should we go with this instead?

```
  {% webhook-entry provider="Hookdeck" hash="sha256" encode="base64" rotation="❌" versioning="❌" timestamp="❌" link="https://hookdeck.com/docs/destinations#receiving-webhook-events" /%}
```

**Comment by leetrout** [comment]
> Hi @leetrout .
> 
> Thanks for the PR <3.
> 
> According to https://hookdeck.com/docs/destinations#receiving-webhook-events , Hookdeck notifications are base64 encoded.
> 
> Should we go with this instead?
> 
> ```
>   {% webhook-entry provider="Hookdeck" hash="sha256" encode="base64" rotation="❌" versioning="❌" timestamp="❌" link="https://hookdeck.com/docs/destinations#receiving-webhook-events" /%}
> ```

My bad, fixed, thank you!

**Review by sudobinbash — APPROVED** [review]
LGTM. Thank you @leetrout <3

**Comment by leetrout** [comment]
@sudobinbash anything preventing a merge?

**Comment by sudobinbash** [comment]
ha! forgot to merge 🤦🏽‍♂️. Sorry for the wait @leetrout

**Comment by sudobinbash** [comment]
done.

**Comment by sudobinbash** [comment]
Heyo @leetrout   👋

Thanks for contributing to webhooks.fyi.
We're launching our site on [Product Hunt tomorrow](https://www.producthunt.com/posts/webhooks-fyi) and I'd love to include our contributors as makers (to spread the love and street creds).

Please sign up to [producthunt.com](https://producthunt.com) and send me your profile url here if you would like to be included and I'll take care of the rest.

ty,
Fred

**Pull request merged**
